name: planning-poker
on:
  push:
    branches:
      - master

env:
  BACK_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}

jobs:
  build-and-push-core:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Java setup
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven package
        run: mvn --batch-mode --update-snapshots package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.BACK_IMAGE }}
          tags: latest
          labels: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.BACK_IMAGE }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-core]
    steps:
      - name: show
        run: ls -la
